PromptsMask0:
  - "Find the ground level of the building in the satellite image."
  - "Locate the lowest floor of the structure from the aerial view."
  - "Identify the base level of the building shown in the satellite photo."
  - "Pinpoint the ground floor of the architectural design from the sky."
  - "Determine the lowest elevation of the building in the satellite view."
  - "Discover the building's foundation from the aerial perspective."
  - "Highlight the ground level of the structure seen from above."
  - "Spot the lowest tier of the building in the satellite imagery."
  - "Recognize the base floor of the building in the aerial picture."
  - "Retrieve the image of the ground floor of the building from the satellite view."

PromptsMask1:
  - "Show me images of buildings with one floor."
  - "Find pictures of single-story buildings."
  - "Retrieve images of small houses."
  - "Show me short-size buildings."
  - "Find pictures of one to four-story buildings."
  - "Retrieve images of houses with a small number of floors."
  - "Show me buildings with a maximum of four levels."
  - "Find pictures of short-height structures."
  - "Retrieve images of one to four-story constructions."
  - "Show me houses with limited floor levels."

PromptsMask2:
  - "Show me images of buildings with five to ten floors."
  - "Find pictures of medium-sized constructions."
  - "Retrieve images of buildings with a moderate number of levels."
  - "Show me medium-height buildings."
  - "Find pictures of five to ten-story buildings."
  - "Retrieve images of structures with a medium number of floors."
  - "Show me buildings with a range of five to ten levels."
  - "Find pictures of moderately tall buildings."
  - "Retrieve images of five to ten-story constructions."
  - "Show me medium-sized houses."

PromptsMask3:
  - "Show me images of tall buildings exceeding 10 floors."
  - "Find pictures of skyscrapers with more than 10 levels."
  - "Retrieve images of very tall constructions."
  - "Show me skyscrapers with over 10 stories."
  - "Find pictures of buildings taller than 10 floors."
  - "Retrieve images of extremely tall structures."
  - "Show me buildings with a height greater than 10 levels."
  - "Find pictures of skyscrapers that exceed 10 stories."
  - "Retrieve images of buildings soaring above 10 floors."
  - "Show me very tall buildings and skyscrapers."
